### ISSUE TITLE
Demultiplex custom barcode

### ISSUE THREAD

**Issue by Seongmin-Jang-1165** [nanoporetech/dorado#1051]
# Issue Report

## Please describe the issue:

hello. i want to demultiplex direct RNA seq data(POD5 format). 

i referenced the description "Custom Barcode Arrangements", but ther error is occured. i attach the error message.  what is the problem of my code or something else..?

![화면 캡처 2024-09-30 155404](https://github.com/user-attachments/assets/2f94046e-6880-44c3-b8b1-2585e7454066)

[arrangement]
name = "custom_barcode"
kit = ""

mask1_front = ""
mask1_rear = ""
mask2_front = ""
mask2_rear = ""

# Barcode sequences
barcode1_pattern = "BC_C%02i"
barcode2_pattern = "BC_M3%02i"
first_index = 1
last_index = 2
rear_only_barcodes = true

## Scoring options
[scoring]
max_barcode_penalty = 11
barcode_end_proximity = 75
min_barcode_penalty_dist = 3
min_separation_only_dist = 6
flank_left_pad = 5
flank_right_pad = 10
front_barcode_window = 175
rear_barcode_window = 175
midstrand_flank_score = 0.95

barcode_fastq
>BC01
GTACTTTTCTCTTTGCGCGG
>BC02
GTGATTCTCGTCTTTCTGCG

**Comment by Seongmin-Jang-1165** [comment]
i used SQK-RNA004 library kit and barcoding with 2 specific-adapter

**Comment by malton-ont** [comment]
Hi @Seongmin-Jang-1165,

The parser is saying you have an error in the line `name = "custom_barcode"`. There doesn't seem to be an error present in what you've pasted here, so please check the original file.

You also have some other issues:
* Your fasta file does not appear to be valid - identifier lines should begin with a `>`
* Your `barcode1_pattern` does not match the identifiers in your fasta
* You specify `barcode1_pattern` and `barcode2_pattern`, but also `rear_only_barcodes` - if you only have rear barcodes then there can be no `barcode2_pattern`
* A custom barcode arrangement must specify at least one of `mask1_front` or `mask2_front` - it looks like you're trying to sidestep this to perform adapter detection instead of barcodes? Dorado does not support this.

**Comment by Seongmin-Jang-1165** [comment]
hi @malton-ont 

thank for your advice! it helps me a lot 

i prepare library with target-specific adapter and put the barcode sequence into adapter. so it seems like detecting adapter...
