### ISSUE TITLE
Unable To Use Automatic Model Selection

### ISSUE THREAD

**Issue by pinkfairy57** [nanoporetech/dorado#1076]
Hello,

I tried using different models to specify the chemistry but was unable to find the right one. So I tried doing the automatic model selection by

dorado basecaller hac --models-directory /path/to/models/ --no-trim /path/to/file.pod5 > /path/to/calls.bam

I also tried hac@latest in the place of hac.

The models directory has all the downloaded models I got from using “dorado download --model all”

The error I am getting is:

Running: "basecaller" "hac" "--models-directory" “/path/to/models/" "--no-trim" “/path/to/file.pod5"
[error] No supported chemistry found for flowcell_code: 'UNKNOWN_FLOWCELL' sequencing_kit: 'SQK-LSK109' sample_rate: 4000
[error] This is typically seen when using prototype kits. Please download an appropriate model for your data and select it by model path
terminate called after throwing an instance of 'std::runtime_error'
what(): Could not resolve chemistry from data: Unknown chemistry
Aborted (core dumped)

 When I did: pod5 inspect debug <data.pod5> | grep -E "flow_cell_product_code|sequencing_kit" It showed
sequencing_kit': 'sqk-lsk109
flowcell_type': 'flo-min106

Did I write the command correctly? If not, how else do choose an automatic model? Please help me.

**Comment by HalfPhoton** [comment]
```text
[error] No supported chemistry found for flowcell_code: 'UNKNOWN_FLOWCELL' sequencing_kit: 'SQK-LSK109' sample_rate: 4000
```

The automatic model selection is checking all the files and I think what's going on here is that one (or more) of them has an unknown flowcell code.

From your example: FLO-MIN106 is [registered](https://github.com/nanoporetech/dorado/blob/c3a2952356e2506ef1de73b0c9e14784ab9a974a/dorado/models/kits.cpp#L48C14-L48C24) and should be part of the r9.4.1 chemistry.

Can you double check **all** your files have  `flowcell_type': 'flo-min106'`?

You might also get some more info from adding verbose logging with `-vv`.

**Comment by pinkfairy57** [comment]
Hello,

Thank you for responding. I only used one pod5 file for conversion. I am not sure if it matters but here's some extra info.

sequencing_kit: sqk-lsk109
flow_cell_product_code: 
had nothing shown for the flow_cell_product_code
flowcell_type': 'flo-min106

Is the lack of flow_cell_product_code, causing the issue?

Also, in general, is
dorado basecaller hac --models-directory /path/to/models/ --no-trim /path/to/file.pod5 > /path/to/calls.bam
the correct way to call for automatic model selection?

**Comment by HalfPhoton** [comment]
Yes that's the problem - all input pod5 files must resolve to the same chemistry for the automatic model selection to proceed. 

You can still basecall these files (with missing metadata) by selecting the model manually using a model **path** instead of the model complex ( fast / hac / sup ). I'd recommend checking from wherever you sourced these files that they're the chemistry you believe them to be or your basecalls may be incorrect. 

From the data you've shared so far I believe they're from the `R9.4.1` chemistry


If you download all the models with `dorado download --models all --models-directory /path/to/models` then the models be downloaded into `/path/to/models`. You can then re-use these models with the _**automatic model selection**_ by specifying a [model complex](https://github.com/nanoporetech/dorado?tab=readme-ov-file#automatic-model-selection-complex) (`dorado basecaller hac data/ --models-directory /path/to/models/ ... `). 

However, as you're having issues with the metadata causing the model selection to fail, simply use : `dorado basecaller /path/to/models/dna_r9.4.1_e8_hac@v3.3 data/ ...`. You don't need the `--models-directory` argument in this case as you're doing all the necessary work by specifying the path.


Best regards,
Rich
