### ISSUE TITLE
demuxing with custom dual barcoding

### ISSUE THREAD

**Issue by nr0cinu** [nanoporetech/dorado#1092]
Hi, 

is it possible to perform demultiplexing with dorado using unique or combinatorial dual barcoding?

We have a custom barcoding set up, and we [followed the documentation to set up a custom kit](https://github.com/nanoporetech/dorado/blob/master/documentation/CustomBarcodes.md), however this outputs one file per barcode, and not one file per combination of barcodes.

Here is a minimal example of how our custom barcoding looks like:

- Sample A: barcode 01 + barcode 02
- Sample B: barcode 01 + barcode 03
- Sample C: barcode 02 + barcode 03
- ...

where these are BARCODE_1 and BARCODE_2 following the schema: `5' --- ADAPTER/PRIMER --- BARCODE_1 --- TRAILING_FLANK_1 --- READ --- RC(TRAILING_FLANK_2) --- RC(BARCODE_2)--- 3'`

Thanks!
Bela

Dorado version: 0.8.1+c3a2952

Dorado command: `dorado demux --kit-name BC --barcode-arrangement barcode_arrangement.toml --barcode-sequences barcode_sequences.fna --output-dir out --threads 4 --verbose --emit-fastq --emit-summary --barcode-both-ends --no-trim fastq_pass`

**Comment by nr0cinu** [comment]
Hi Malton!

Thanks for the quick answer! :)

Any plans of implementing combinatorial/unique dual indexes in dorado?

By chance, can you give any recommendations for a alternative for demultiplexing then? Right now, I am leaning towards cutadapt, as it supports this kind of demultiplexing.

Thanks,
Bela

**Comment by malton-ont** [comment]
Hi @nr0cinu,

We are looking at supporting combinatorial barcoding, but not really in the manner that you have described - we're looking more at two full barcodes (inner and outer) on a read rather than the front and rear being from different barcodes.

Our current recommendation would be to create two custom kits: one for the front barcode and one for the rear barcode (with the `rear_only_barcodes = true` set in the second kit), and perform two rounds of demultiplexing. You would then need to manually check that this has generated a permitted combination.

**Comment by nr0cinu** [comment]
Okay, thank you for the infos!
