### ISSUE TITLE
dorado basecaller: model dna_r10.4.1_e8.2_400bps_hac@v5.0.0 slower than dna_r10.4.1_e8.2_400bps_sup@v5.0.0

### ISSUE THREAD

**Issue by davidebolo1993** [nanoporetech/dorado#1113]
# Issue Report

## Please describe the issue:

Hi all,

I was testing dorado basecaller (v0.8.0) on a subset of pod5 from the open-data, specifically `giab_2023.05/flowcells/hg002/20230428_1310_3H_PAO89685_c9d0d53f/pod5_pass/`. I'm running the same `dorado basecaller` command you see below w/ 3 models:
1. dna_r10.4.1_e8.2_400bps_fast@v5.0.0
2. dna_r10.4.1_e8.2_400bps_hac@v5.0.0
3. dna_r10.4.1_e8.2_400bps_sup@v5.0.0
```bash
start=$(date +%s)
dorado basecaller \
	-x cuda:all \
	--emit-fastq \
	--output-dir $model_type/$pod5_basename \
	-v \
	dna_r10.4.1_e8.2_400bps_$model_type@v5.0.0 \
	$pod5
end=$(date +%s)
echo "Elapsed: $(($end-$start))"
```
where it's easy to guess that $pod5 is the single pod5, $pod5_basename its basename and $model_type on of {fast,hac,sup} (those were downloaded before the test). This is run on a slurm cluster, on a computing node equipped with 4 Tesla V100-SXM2-32GB.
Calculating the average time spent basecalling for the 4 models I get something surprising (to me).

fast: 41.8889
hac: 213.178
sup: 84.6333

The numbers you see are the average time (seconds) required for basecalling a single pod5. Is it expected that the hac model is ~5 times slower than fast and >2 times slower than sup? I've double-checked hac results but those are confirmed on my side. Let me know if you need additional information to try and reproduce the issue (if any).

**Comment by HalfPhoton** [comment]
Hi @davidebolo1993, as you're seen the auto batch size is what's taking almost all the time getting set-up. 
It's quicker for sup as there are many fewer batch sizes to test because it's a much larger model.

We expect the auto batchsize process to only be a small part of your basecalling time but as you're basecalling a very small dataset it's a problem.

You can set the `--batchsize 9996` yourself to skip this process and get set-up quicker.

Best regards,
Rich
