### ISSUE TITLE
Recommended max_barcode_penalty for a given barcode length 

### ISSUE THREAD

**Issue by lonsbio** [nanoporetech/dorado#1119]
The example [custom barcode docs](https://github.com/nanoporetech/dorado/blob/release-v0.8/documentation/CustomBarcodes.md) give the following scoring options:

```
## Scoring options
[scoring]
max_barcode_penalty = 11
barcode_end_proximity = 75
min_barcode_penalty_dist = 3
min_separation_only_dist = 6
flank_left_pad = 5
flank_right_pad = 10
front_barcode_window = 175
rear_barcode_window = 175
midstrand_flank_score = 0.95
```

What is the length of the barcodes that gave this example? I have 10bp barcode and trying to understand the tolerance for errors intended with these example values.

**Comment by lonsbio** [comment]
Thanks for the clarification @malton-ont , that really helps a lot! I had several runs with [[scoring]] omitted and those default values would explain some of the missing reads being assigned unclassified with such a generous edit distance relative to the barcode length. 

Reigning in the edit distance ~5 has helped, but I still get quite a few unclassified reads.

The custom RNA-seq (cDNA) hs the following structure: 

5' --- ADAPTER---PRIMER1 --- READ ---  ADAPTER---PRIMER2 --- BARCODE_1 --- UMI --- 3'

From the documentation, I infer we need the PRIMER2 as the mask1 since there is no other leading flank, 

```
mask1_front = "PRIMER2"
mask1_rear = ""
mask2_front = ""
mask2_rear = ""
rear_only_barcodes = true
```
Does the lack of a distinct flank region and/or the UMI affect the scoring parameters to use?

**Comment by malton-ont** [comment]
@lonsbio,

Potentially, yes. Dorado includes context regions of length `max(flank_left_pad, len(mask1_front))` and `max(flank_right_pad, len(mask1_rear))` around the barcode when evaluating the edit distance, and this needs to be accounted for in the `max_barcode_penalty` score. Since you have no `mask2_rear` that context region will be 0, so you'd likely want a lower score than the default as you've discovered.

You may also need to lower `min_barcode_penalty_dist` (the minimum difference between the best two barcode edit distances if the best barcode passes `max_barcode_penalty`) and/or `min_separation_only_dist` (the minimum distance between the best two barcode edit distances if the best barcode does not pass `max_barcode_penalty`). This is because with shorter barcodes, the difference in the edit distances for different barcodes is likely to be smaller.

**Comment by lonsbio** [comment]
Thanks @malton-ont, I will do some comparisons and try to optimise for my barcode structure. 

One confusion with the `rear_only_barcodes` setting is whether that implies that the front or rear mask is needed?

Trying with empty strings for mask1* gives this error:

```
  what():  At least one of mask1_front or mask1_rear needs to be specified.
```

whereas empty strings for mask2* gives: 
```
  what():  At least one of mask2_front or mask2_rear needs to be specified.
```

and it only runs when both are defined with PRIMER2 as above.

**Comment by malton-ont** [comment]
@lonsbio,

You should omit `mask2_*` entirely rather than providing an empty string.
