### ISSUE TITLE
dorado run time- super high accuracy, promethION

### ISSUE THREAD

**Issue by YiJessePi** [nanoporetech/dorado#1132]
I'm executing dorado on promethION flowcells while basecalling with super-accuracy and some methylations.
I'm running it per pod5 file, which I typically have 60-70 pod5 files per run.
Each pod5 file is being executed by Tesla V100 with 16-32G mem and takes ~10 hours to run, so for the whole flowcell I need at least 600 GPU hours (which typically takes 5 days).
Does it sounds reasonable to you?
Does executing on each pod5 file separately is the correct way to do so or it's better to merge?
 
## Run environment:
- Dorado version: 0.7.3
- Dorado command: dorado basecaller -v --kit-name <kit>- --trim 'all' sup@v5.0.0 <file> --modified-bases 4mC_5mC 6mA 
- Hardware (CPUs, Memory, GPUs): GPU Tesla V100 with 16-32G
- Source data type (e.g., pod5 or fast5 - please note we always recommend converting to pod5 for optimal basecalling performance): pod5
- Details about data (flow cell, kit, read lengths, number of reads, total dataset size in MB/GB/TB):  PromethION ~150GB

**Comment by Kirk3gaard** [comment]
Any speedups expected from including the modifications in the sup model from the start rather than having it is a set of separate models? 

I am curious as to whether basecalling DNA with 4 "normal" bases and 3 modified bases into 4 bases with the normal models is much faster than having a model with 7 "bases" and how it affects accuracy. 
(Also I still find it puzzling that there is no "all" option for calling mods. )

**Comment by Kirk3gaard** [comment]
Also @YiJessePi I can recommend getting a "gaming" computer with one more RTX4090 GPUs to speed up your basecalling. The V100 cards are very slow compared to the newer GPUs.  The A100 and H100 are kinda pricy options.

**Comment by malton-ont** [comment]
> Any speedups expected from including the modifications in the sup model from the start rather than having it is a set of separate models?
> 
> I am curious as to whether basecalling DNA with 4 "normal" bases and 3 modified bases into 4 bases with the normal models is much faster than having a model with 7 "bases" and how it affects accuracy. (Also I still find it puzzling that there is no "all" option for calling mods. )

@Kirk3gaard Guppy used to have "mod+canonical" models available I believe - the issue here is that running an equivalent canonical-only model then might not give the same basecalled sequence, since the mod+ model has additional cross-base confusion possibilities. The choice in dorado was to separate the two processes for improved reproducibility - you'll get the same sequence regardless of whether you perform modification calling. We're continually working on performance improvements.

We're still investigating the possibility of an "all" mods option, but it raises the question of _which_ "all", since dorado is not currently capable of running multiple modbase models against the same canonical base. For example, should "all" include `4mC_5mC` or `5mC_5hmC`? This issue only gets more complicated as more models are introduced.
