### ISSUE TITLE
Is it possible to perform demux while basecalling?

### ISSUE THREAD

**Issue by liuzhen51032** [nanoporetech/dorado#1140]
The current workflow in Dorado is to perform basecalling first and then barcode demux. Is it possible to perform these two steps in a single process?

**Comment by malton-ont** [comment]
Hi @liuzhen51032,

It's possible to barcode inline with basecalling, but this will not generate separate files per barcode - for this you will still need a separate `demux --no-classify` step.

**Comment by HalfPhoton** [comment]
https://dorado-docs.readthedocs.io/en/latest/barcoding/barcoding/#in-line-with-basecalling

**Comment by ckdabk** [comment]
Hello, I have a question pertaining to basecalling and demuxing. I'm using Dorado 0.8.0 and, as per [this post](https://github.com/nanoporetech/dorado/issues/1020#issuecomment-2361691142), the workaround is to basecall and then demux separately. Could you tell me my commands are right?

Basecalling:
`dorado basecaller hac --no-trim /path/to/pod5/ > /path/to/output_call.bam` 

Demuxing:
`dorado demux --kit-name SQK-NBD114-24 --output-dir /path/to/outputs/   /path/to/output_call.bam`

The reason I'm asking is because I got 19 different barcode .bam files and one unclassified.bam file running the above, and my wet lab counterpart insists that they only used two barcodes. I should also add that I'm waiting for my sysadmin to update Dorado to 0.8.3 so in the mean time I'm stuck on 0.8.0. Thanks for your help.

**Comment by malton-ont** [comment]
@liuzhen51032,

The commands look fine. How many reads are there in each file? There are 24 possible barcodes in that kit, and a small number of misclassified reads may not be unexpected. If you want to fully restrict to only the specified barcodes you can use a sample sheet - see https://dorado-docs.readthedocs.io/en/latest/barcoding/sample_sheet/.

**Comment by JWDebler** [comment]
@ckdabk you always get some wrongly called barcodes when demultiplexing, have you checked how much data is in the 17 barcode bam files that your wetlab friend didn't use? It's probably just a few reads, so you can just delete them.

**Comment by ckdabk** [comment]
@JWDebler @malton-ont thank you both for your previous replies. 

I am currently attempting to basecall and demultiplex a POD5 file, and then run [MAGeCK](https://sourceforge.net/p/mageck/wiki/Home/) analysis on the subsequent output. 

I'm using Dorado 0.8.3 and my commands are:
`dorado basecaller --kit-name SQK-NBD114-24 hac /path/to/pod5/ > /path/to/output_call.bam `
`dorado demux --emit-fastq --no-classify --output-dir /output/dir/ /path/to/output_call.bam`

Based on the documentation, I believe that my commands are correct. However, when I subsequently run MAGeCK, I get an error that says `Cannot automatically determine the --trim-5 length. Only 0.0 % of the reads can be identified.` I assume my MAGeCK commands are correct, because in the past I've been able to use it with outputs from simplex basecalling. 

I've also performed a BLAST search, using the forward and reverse sequences of BC01 from the [barcoding kit](https://nanoporetech.com/document/ligation-sequencing-amplicons-native-barcoding-v14-sqk-nbd114-24), and the BLAST results show that there are bits of the barcode still left on both ends of my reads. 

I'm not sure what I'm doing wrong. This is my first time trying the Dorado -> MAGeCK pipeline with barcoded reads so thank you for your patience and help.

**Comment by JWDebler** [comment]
@ckdabk I can't speak to MAGeCK, but in my experience dorado's adapter and barcode removal leaves a lot of adapter and barcode sequnences in your reads, even if you run 'dorado trim' over your already 'trimmed' reads. If you want to make sure those are gone you can hard trim 75 bp from the front and end of your read with a tool like [chopper](https://github.com/wdecoster/chopper). 
I'm not sure this matters, but have you tried putting 'hac' directly after 'dorado basecaller'? I'm not sure if dorado needs some arguments to be positional.

**Comment by malton-ont** [comment]
@ckdabk,

I'm not familiar with MAGeCK I'm afraid. My suggestions would be:

1. Run `dorado` with `-v` - this will give you a breakdown of the barcode classifications
2. Does MAGeCK require fastq files instead of bam? Try with `--emit-fastq`
3. Does MAGeCK require the barcodes to still be present? Try with `--no-trim` or `--trim adapters`

Unless there is a problem with the actual barcode classification in step 1 then I don't think this is a dorado issue.

**Comment by ckdabk** [comment]
I've been able to fix the issue, and I'd like to thank you both again for your help.
