### ISSUE TITLE
NVIDIA RTX A2000 6GB not supported

### ISSUE THREAD

**Issue by husamia** [nanoporetech/dorado#150]
I have the NVIDIA RTX A2000 6GB which I have been using with guppy gpu. I want to use dorado but it seems that my GPU isn't supported. is there a way I can modify the required memory?

c:\dorado-0.2.4-win64\models>nvidia-smi --list-gpus
GPU 0: NVIDIA RTX A2000 (UUID: GPU-e8001bfd-2d23-337a-40af-f58c6b9fbe72)

```
[2023-04-18 15:22:58.976] [info] > Creating basecall pipeline
[2023-04-18 15:22:59.192] [warning] Auto batchsize detection failed. Insufficient memory, required 8GB, available 5GB
```

**Comment by iiSeymour** [comment]
@husamia the presets are set here https://github.com/nanoporetech/dorado/blob/master/dorado/utils/cuda_utils.cpp#L243 you'll need to add `6` to the `breakpoint` vector and a new entry in `batch_sizes` the maximum batch sizes for each model _(fast, hac, sup)._

**Comment by husamia** [comment]
so I need to modify the cuda_utils.cpp at two lines:
first modification is ading a 6 to the breakpoint vector like so?
243     const std::vector<int> breakpoints{6, 8, 12, 16, 24, 32, 40};
second modification is adding new line at 246 for 6GB but what values do I put in the vector for the 6GB?
         {?, ?, ?},     // 6GB

then compile dorado? I am using windows precompiled dorado to run in Windows. not sure how easy it would be to compile it in windows..

**Comment by iiSeymour** [comment]
@husamia sorry, I thought you were asking about how you could add a patch for 6GB GPUs.

You can modify the GPU memory used with the CLI option `-b, --batchsize`. The default value for `--batchsize` is 0 which means the presets are used and the best batch size is found. Because we don't have a preset for 6GB GPUs the default selection is 128 for all model sizes. https://github.com/nanoporetech/dorado/blob/master/dorado/utils/cuda_utils.cpp#L263
 
So, if you have spare GPU memory available when running the fast/hac model you can increase the batchsize closer to the 8GB presets _(768 fast, 384 hac)_, and if the SUP model is using too memory try 96.

**Comment by husamia** [comment]
@iiSeymour `--batchsize 96` is working 

thank you

**Comment by husamia** [comment]
@iiSeymour `--batchsize 96 ` doesn't give me an error message but at some point the Reads processed stalls. So I changed it to 85 and it seems to get passed the previous number. Is there a way to debug this to figure out why it stalling?

**Comment by iiSeymour** [comment]
GPU memory allocation is much better in recent releases of dorado and is no longer based on supported presets.
