### ISSUE TITLE
FR: give some control over minimap2 behaviour | write both (un)aligned BAMs

### ISSUE THREAD

**Issue by sklages** [nanoporetech/dorado#196]
with versions prior to `0.3.0` we ran basecalling (with modified-bases) separated from mapping and methylation calling.
On one hand, because `dorado` didn't support it yet, and on the other hand to gain some flexibilty. 
E.g. we have by far more CPU servers (for all non-basecalling stuff) than GPU servers, so we can more efficiently use our ressources.

Now that `dorado` is capable of mapping "on-the-fly" without much loss in overall speed I'd like to propose two enhancements which would make it more flexible:

- give some control over minimap2
In contrast to `bonito` `dorado` now keeps "supplementary alignments" ... but also emits "secondary alignments" which are of no use for some people .. so here I'd like to have control over minimap's `--secondary=yes|no` parameter. Other basic parameters may be of interest as well.
- optionally output unaligned BAM along with the mapping
In case I'd like to re-map my data on sth like `hg40` or so, I don't want to convert my aligned BAM to unaligned BAM. Ideally I would direct `dorado` to also write unaligned BAM data (just as it would if we would omit `--reference` ) along with the aligned BAM.

What do you think?

**Comment by tijyojwad** [comment]
Hi! Thanks for your feedback and request.

> give some control over minimap2

This is a very reasonable ask. We would like to expose more options, at the same time not have to re-implement all mm2 options. If you could share the subset you'd be interested in that would be great.

> optionally output unaligned BAM along with the mapping

this one I'll need to discuss with our team. writing to 2 outputs is possible but not ideal since it may interfere with overall basecalling speed. I think perhaps in your use case generating fastq/unaligned bams from `dorado` is better, so you can use it to map against any reference?

**Comment by iiSeymour** [comment]
@sklages `dorado aligner` allows you remapped previously aligned calls and avoids conversion.

```
$ dorado aligner hg40.mmi mapped.bam > hg40.mapped.bam 
```

**Comment by wilsonte-umich** [comment]
I'd also like more minimap2 control. In addition to --secondary, I routinely adjust the -r (bandwidth) option.

**Comment by iiSeymour** [comment]
@sklages @wilsonte-umich we've included these options to `dorado aligner` in v0.4.0.
