### ISSUE TITLE
 toml::parse: file open error

### ISSUE THREAD

**Issue by achang44** [nanoporetech/dorado#241]
input code
` ./dorado basecaller dna_r9.4.1_e8_hac@v3.3_5mCG@v0 pod5s --modified-bases-models /mnt/c/Users/qbiol/Desktop/Nanopore/Software/dna_r9.4.1_e8_hac@v3.3_5mCG@v0/ >calls.sam`

This is the error message:
`[2023-06-15` 15:28:40.426] [info] > Creating basecall pipeline
[2023-06-15 15:28:40.620] [error] toml::parse: file open error -> `dna_r9.4.1_e8_hac@v3.3_5mCG@v0/config.toml`

I have verified the file path, and have been able to verify the computer can find and read the file by using 'head' command.

**Comment by malton-ont** [comment]
There look to be two issues with your command.

Firstly, the model parameter should be the basecall model rather than a modified bases model (i.e. the model name should not contain `5mCG` etc)

Secondly, while you've specified a full path to the modified bases model, you've only specified the name of the model for the basecall model. Unless you've downloaded the model into the local folder, this will also need to be a path (full or relative) to the download location. Assuming you have downloaded the basecall model into the same folder then your command should look like:
`./dorado basecaller /mnt/c/Users/qbiol/Desktop/Nanopore/Software/dna_r9.4.1_e8_hac@v3.3 pod5s --modified-bases-models /mnt/c/Users/qbiol/Desktop/Nanopore/Software/dna_r9.4.1_e8_hac@v3.3_5mCG@v0/ > calls.sam`

**Comment by tijyojwad** [comment]
Hi @achang44 - hopefully the above response helped you. We're closing the issue for now. If you have more questions, please re-open. Thank you!

**Comment by Larysha** [comment]
Hi - I am having a similar problem:

#!/bin/bash

dorado="/mnt/c/Users/Rish/dorado/bin/dorado.exe"
model="model=/mnt/c/Users/Rish/dorado/bin/dna_r9.4.1_e8_sup@v3.6"
${dorado} basecaller ${model} --device cuda:all ./pod5-files/ > sup_calls.bam

and get the same error:
[2023-08-02 14:24:50.605] [info] > Creating basecall pipeline
[2023-08-02 14:24:50.643] [error] toml::parse: file open error -> /mnt/c/Users/Rish/dorado/bin/dna_r9.4.1_e8_sup@v3.6/config.toml

my file paths are correct and the `config.toml` is in the /mnt/c/Users/Rish/dorado/bin/dna_r9.4.1_e8_sup@v3.6 directory with full permissions - does anyone know why this error occurs ?
