### ISSUE TITLE
Dorado crashing the moment I run it

### ISSUE THREAD

**Issue by Vsd1106** [nanoporetech/dorado#242]
I have downloaded dorado-0.3.0-win64 and when I run the dorado executable, the window crashes instantly and I cannot see if there is an error nor read if there is one in time to fix it.

**Comment by malton-ont** [comment]
It sounds like you are trying to launch dorado by double-clicking the executable. Dorado is a command line application, and needs to be run via the console in order to specify the parameters such as subcommand, model and input data path. This can be done via a git-bash terminal, powershell, or good old cmd. Please see https://github.com/nanoporetech/dorado#running for further information, or begin with `dorado -h` to view the help.
