### ISSUE TITLE
Feature request: Argument to limit number of CPUs used

### ISSUE THREAD

**Issue by Ge0rges** [nanoporetech/dorado#291]
It would be great to set a cap on dorado to limit the amount of CPU resources used, much like can be done for GPUs.

**Comment by vellamike** [comment]
The feature you are asking about is not currently being developed. The Dorado software is primarily designed to be utilised in conjunction with GPUs. The CPU functionality exists for convenience and is not the intended method for substantial work, due to its relatively slower basecalling speed.

Nevertheless, it may be possible for you to restrict the usage of CPUs by using the `taskset` command as illustrated below:

```
taskset -c 0,1,3 ./dorado basecaller -x cpu ...
```

This command will allow you to specify the CPU cores that the Dorado software can use during operation. Please ensure you adjust the parameters to match your system's specifications.
