### ISSUE TITLE
download address of the models ?

### ISSUE THREAD

**Issue by Imoteph** [nanoporetech/dorado#352]
Hi

is it possible to post the links to the models here, so I can load them separately, as the machine running dorado has not connection to download them?

**Comment by sklages** [comment]
Just use another machine with internet connection, download the models and copy the files to your basecalling machine. It is just as easy as using download links. 
Model (and thus file) names may change (new models, new versions whatever), so it is better (and safer) to **not** use direct file links IMHO.

**Comment by Imoteph** [comment]
Well only if you expect that the outside machine is a linux device ;), which is not the case always, like in my case. Anyway, thanks for the response!

Quick question, why are the models are not shipped directly or tracked here in the repo? 

Issue can be closed :)

**Comment by sklages** [comment]
@Imoteph - well, there are precompiled binaries, MacOS and Windows as well .. do you have any special system?

**Comment by iiSeymour** [comment]
@Imoteph models are not tracked in the repository because they are large binary files and not suitable for version control systems such as git. @sklages is correct you don't need a Linux device but if you really want to grab the models directly from the source see: https://github.com/nanoporetech/dorado/blob/master/dorado/utils/models.h#L9. Just concatenate the `URL_ROOT`, `URL_PATH`, and the model name.

**Comment by Imoteph** [comment]
Thanks for all the comments! @sklages  and @iiSeymour 

 I was not aware of the other pre-compiled binaries thanks for pinpointing but the the link into the src is super helpful!

@sklages yes, my frontend Windows system is quite limited but this is a unique case.  

best and thanks for your help!
