### ISSUE TITLE
How does dorado/dorado-server resume?

### ISSUE THREAD

**Issue by billytcl** [nanoporetech/dorado#353]
I am running dorado/dorado-server on a SLURM cluster, and there is a very high performance partition that I can access but it can kick me off spontaneously if the "owner" of a machine starts up a job, but then it will restart the job when there is space in the queue.

When I use resume, does it scan all of the log files to build a comprehensive list of all the reads that have been called, or does it use only the most recent log file? Sometimes it will kill the process very quickly (eg. during the resume preflight or when loading the genome index). I think this happened one time with guppy and it appeared to start from the beginning because of this (eg. the log would be resuming from X fast5s).

**Comment by billytcl** [comment]
Hi, just bumping this -- any thoughts from the ONT dorado team?

**Comment by MarkBicknellONT** [comment]
Hi @billytcl,

When you are using the `dorado_basecall_server`, the client will interrogate _all_ the log files in the output directory to find completed files and batches from previous interrupted runs. This means that it should attempt to recover previous basecalls from multiple interruptions for you.  However the resume process is not totally infallible: As you have seen, if the server is terminated during the resume recovery process, some of the previous successful basecalls may be lost, as the previous log file might not be chained back to older executions of the basecaller correctly.

For this reason it might not be optimal to rely solely on the resume operation in an environment where you are routinely expecting execution to be interrupted.  A belt-and-braces approach would be to split the input files into smaller batches and run each one of those through the basecall server with the --resume option also enabled.  Then, if the resume fails due to an early termination, you only have to restart your sub-batch.

The standalone `dorado` application also supports `--resume-from`.  This works in a quite different way, where you provide it with a previous basecall output file, and it will extract any complete reads which it finds in that file.  It then skips those read ids when processing the remaining input.

**Comment by billytcl** [comment]
Thanks for this. How are the log files chained? I see a line that says
“resuming from” an older log file. So I’m guessing if it’s interrupted at
any point before the chain is established then it breaks down?

If you could explain how the the chaining and log files work, it may be
possible for me to whip up a “pre-flight” script that removes the most
recent log file from an aborted resume that didn’t manage to chain
properly. That way it would be as if the offending job never ran…

Ideally I would use stand-alone dorado but I need the barcoding!

**Comment by MarkBicknellONT** [comment]
Hi @billytcl,

The process goes like this:

- All the log files in the output folder are added into a time-ordered list.
- They are then sorted into groups for each previous execution of the basecaller (if a log file goes over 5MB, a new file is started, so a single execution may have produced multiple files).  Specifically, the first log file for any given execution will contain the header "ONT basecalling software", which we look for.
- For the current run's log file, we will emit a line saying "Resuming basecall from previous logfile: " and the name of the _first_ logfile from the most recent previous run.  (If the basecall process is killed before this line is emitted, that is what causes the resumption chain of previous runs to be broken.)
- We then go through the previous run log files looking for lines containing "Completed batch" which indicates a batch of reads were successfully written to the output folder.  These batches and the read ids within them are recorded, so we can skip them.
- If we find a line in the previous run's log files that says "Resuming basecall from previous logfile: ", we will recursively iterate down into any historic run as required to extract all the completed batches of reads.
- Once all this iteration has been completed and a list of the fully processed batches and read ids has been created:
 - We will delete any sequence files in the output folder which do not correspond to a completed batch
 - We recover the summary file by renaming the old summary file to sequencing_summary.txt.prev, then copying across all the read entries from completed batches to a new sequencing_summary.txt.
 - Basecalling can now resume.  The already-completed input read files are passed into the basecaller's input list so that they can be skipped.

I think you could set up a script to remove the logs of a previous run if it didn't do anything useful. Look at the newest log file and see if it contains the string "Completed batch".  If not, that run of the basecaller will not have added any progress compared to any existing previous run. In that case, you can delete that log file and no progress will be lost.

We could improve the resume functionality of the server to do something very similar to this, so users don't have to perform this clean-up.  I have raised an internal ticket to add this to the basecall server.

Thanks,

Mark

**Comment by billytcl** [comment]
I don't think "Completed batch" is correct 100% of the time on single large pod5 files (eg from a fast5 convert), because it's clearly writing bam files etc during the whole process. At the very end it says something like:

```
ont_basecall_client_log-2023-09-02_13-03-48.log:2023-09-02 13:04:43.320388 [guppy/info] Dispatched batch 0 containing 1 inputs:
ont_basecall_client_log-2023-09-02_13-03-48.log:2023-09-02 13:11:51.510743 [guppy/info] Completed batch 0
```

I've used the more conservative approach and just moved away files that don't have any "completed" lines in them for individual reads. For example, one of the log files is like this:

```
(base) [billylau@sh02-01n58 /scratch/groups/hanleeji/20211119_PRM_1116/dorado_5mc_prom_pod5] (job 29826275) $ cat ../ont_basecall_client_log-2023-09-02_00-18-05.log 
2023-09-02 00:18:05.574179 [guppy/message] ONT basecalling software version 7.0.8+d4cb05e23, client-server API version 15.0.0
config file:        /home/groups/hanleeji/ont-dorado-server/data/dna_r9.4.1_450bps_modbases_5mc_cg_sup_prom.cfg
input path:         pod5/
save path:          dorado_5mc_prom_pod5/
chunk size:         2000
minimum qscore:     7
records per file:   4000
fastq compression:  ON
alignment file:     /home/groups/hanleeji/hs38_naa.mmi
alignment type:     auto

Use of this software is permitted solely under the terms of the end user license agreement (EULA).
By running, copying or accessing this software, you are demonstrating your acceptance of the EULA.
The EULA may be found in /home/groups/hanleeji/ont-dorado-server/bin
2023-09-02 00:18:05.582904 [guppy/info] crashpad_handler not supported on this platform.
2023-09-02 00:18:05.583337 [guppy/info] Connecting to server as 'ont_basecall_client'
2023-09-02 00:18:05.583561 [guppy/info] connection state: preparing_connection
2023-09-02 00:18:05.583829 [guppy/info] connection state: loading_config
2023-09-02 00:18:05.586178 [guppy/info] connection state: loading_alignment_index
2023-09-02 00:19:21.698263 [guppy/info] connection state: loading_bed_file
2023-09-02 00:19:21.699994 [guppy/info] connection state: connecting
2023-09-02 00:19:21.705332 [guppy/info] Connected to server as 'ont_basecall_client'. Connection id: a2ca826c-bc9a-4c25-a35a-179075ae1483
2023-09-02 00:19:21.705369 [guppy/info] connection state: connected
2023-09-02 00:19:28.825951 [guppy/message] Resuming basecall from previous logfile: dorado_5mc_prom_pod5/ont_basecall_client_log-2023-08-29_15-00-11.log
```

I think I could safely move this one away.

I made a quick preflight check script to do this, and I think it may be useful for other users in this situation. Would appreciate if you can see whether there are any obvious bugs. :)

```
import sys
import os
import glob
import argparse
import shutil

def parse_commandline():
        parser=argparse.ArgumentParser()
        parser.add_argument('--input', help='input folder',required=True)
        parser.add_argument('--out_bad',help='output folder for bad log chains',required=True)

        args=parser.parse_args()
        print(args, file=sys.stderr)
        return args

def main(args):
        files = glob.glob(args.input + "/*.log")
        files.sort(key=os.path.getmtime, reverse=True)

        for file in files:
                with open(file,'r') as log_file:
                        lines = log_file.readlines()
                check_if_completed = ["completed" in x for x in lines]

                if not any(check_if_completed):
                        dest = args.out_bad + "/" + os.path.basename(file)
                        print("Moving " + file + " to " + dest, file=sys.stderr)
                        shutil.move(file, dest)


if __name__ == '__main__':
        args=parse_commandline()
        main(args)
```

**Comment by MarkBicknellONT** [comment]
Hi @billytcl,

Yes, that's correct, if you are loading from a single large input file, that file will be written as a single batch, and so you will only get one batch completion message.  Note that when using a single input file, this means the resume functionality will always restart from the very beginning, as no batches will have been completed by previous runs (unless the previous run successfully completed).  

The reason that BAM files are still being emitted in that case will probably be `--records_per_fastq`, which will be defaulting to 4000 unless you have overridden it.  This argument is somewhat misnamed as it also applies to bam output, so I'll raise an issue to change the name.

Anyway, you are also correct that simply checking for any "completed" messages in the log will also be sufficient - from eyeballing the script, it looks correct.

Kind regards,
Mark

**Comment by billytcl** [comment]
It looks like the resume is working well, but I ran into an interesting issue. As the run gets closer to finishing, the resume process takes up more and more memory and is getting OOM killed by the Slurm cluster.

I'm guessing part of this is that it's working from a single giant pod5 file. The sequencing_summary.txt file is only 47G, but it's failing even on 200GB of allocated memory. Is there a way I can estimate how much memory the resume process will use so I can set it accordingly without guessing?

**Comment by MarkBicknellONT** [comment]
The sequencing_summary.txt file is streamed in and out record by record, so the recovery of that shouldn't be using a lot of memory.  It's simply filtering the old one based on the reads' batch_id.

I suspect the issue might be down to the log files being parsed, before the sequencing summary recovery.  The log files for each previous run are loaded into an in-memory buffer so they can be iterated over more easily.  If the log files are very large, that might be the reason that it is consuming a lot of memory.  How big is the total set of log files in your output folder?

**Comment by billytcl** [comment]
Does dorado-server care which file a specific read came from? I am looking to splitting up the pod5 into chunks but I don't know if I have to start from scratch with the basecalling. That is, if I previously had reads basecalled from "aggregated.pod5", would they be counted if I resumed from a folder containing split pod5s that are in resumable chunks? Or would they be double counted? Or old reads would be deleted from the folder?

**Comment by cjchen5** [comment]
Does dorado --resume-from work with fastq or bam only?

**Comment by vellamike** [comment]
Hi, `--resume-from` will only work from a BAM file.

**Comment by HalfPhoton** [comment]
Closing as the questions have been answered

**Comment by billytcl** [comment]
Hi, just want to bring this up again -- I have a bunch of old fast5s that I want to re-basecall. Is it still recommended to do convert my individual fast5s to individual pod5s (see above thread), or does dorado standalone work well with a single aggregated pod5 now given that it's resuming from a bam file? Some of my older runs have 100k+ fast5s.

**Comment by HalfPhoton** [comment]
@billytcl, it should work fine with a single pod5. 
You can go for a balanced approach with some simple bash to convert batches of N fast5 files if you prefer multiple files with sensible sizes. This approach is discussed in [this thread](https://github.com/nanoporetech/dorado/issues/1210#issuecomment-2598424555).

Best regards,
Rich
