### ISSUE TITLE
dorado - do_read_splitting

### ISSUE THREAD

**Issue by hvanderheyden** [nanoporetech/dorado#367]
Hello there, 

I used the do_read_splitting option combined with the --max_read_split_depth option to split chimeric reads with guppy_basecaller with good results. How to implement these options with dorado? 

Many thanks

**Comment by tijyojwad** [comment]
Hi @hvanderheyden `dorado` doesn't have read splitting enabled for simplex reads yet, but it's currently being worked on. we hope to release it in a few weeks, so stay tuned!

**Comment by susie-ont** [comment]
Hey @hvanderheyden - just to add to Joyjit's answer, the Guppy read splitting method is still available in the Dorado Basecall Server. You can download the Dorado Basecall Server on the Community Downloads page (https://community.nanoporetech.com/downloads). 

Once the Dorado read splitting method is completed in the next few weeks, it will also replace the Guppy method in the Basecall Server. 

Hope this helps!

**Comment by tijyojwad** [comment]
@hvanderheyden simplex read splitting is now supported in dorado [v0.4.0 ](https://github.com/nanoporetech/dorado/releases/tag/v0.4.0) . it's enabled by default, no options necessary

**Comment by rzelle-lallemand** [comment]
> simplex read splitting is now supported in dorado [v0.4.0 ](https://github.com/nanoporetech/dorado/releases/tag/v0.4.0)

@tijyojwad, do you know how to check which version of dorado is included in a given MinKNOW version? I have 23.07.15 installed but the software panel only says:
 
> MinKNOW core:
> 5.7.5
> 
> Guppy:
> 7.1.4
> 
> Bream:
> 7.7.6
> 
> Script Configuration:
> 5.7.11

https://community.nanoporetech.com/downloads lists Guppy v6.5.7 as latest version, so maybe the "Guppy" field in MinKNOW refers to the "Dorado basecall server" version (latest version 7.1.4)? I don't see listed anywhere which dorado version in included in the "Dorado basecall server", assuming the former is bundled with the latter.

I'm asking because we're noticing a huge fraction (rough guess 10-20%) of what look like to be unsplit reads in a recent MinKNOW 23.07.5 / SQK-NBD114-24 run.

**Comment by NanoCoreUSA** [comment]
I see that read splitting has been enabled in Dorado by default now, but was wondering what the default depth is (i.e., analogous to guppy --max_read_split_depth). I'm just wondering how many times Dorado will attempt to split reads. We have very short amplicons in some of our runs so it's likely that multiple reads are concatenated.

**Comment by tijyojwad** [comment]
@NanoCoreUSA - dorado will try to find all split points in a read. there's no additional parameter to specify.
