### ISSUE TITLE
dorado 0.40 demux question 

### ISSUE THREAD

**Issue by echovald1** [nanoporetech/dorado#418]
Hello, I've recently started using dorado (guppy transplant). The 0.40 version of dorado enables demultiplexing options, but I had a two questions.
1. Previously, the fastq output from guppy would be split into fastq_pass and fastq_fail and would correspond to the number of fast5 file inputs; i.e., if 1000 fast5 inputs were recorded, then there would be 1000 fastq outputs.

If we were to use command line to perform demultiplexing afterwards, the files would be sorted into their barcode directory. for example, barcode04 may have 50 or so fastq output files following demultiplexing

With dorado, I wanted to know if it will produce a single demultiplexed fastq output file with the --emit fastq flag, or if it will similarly produce multiple un-concatenated fastq files that would require downstream merging?

2. We have to specify a kit, as indicated by:
"  -h, --help         	shows help message and exits 
  --output-dir       	Output folder for demultiplexed reads. [required]
  --kit-name         	Barcoding kit name. Cannot be used with --no-classify. Choose from: SQK-RPB114-24 VSK-VPS001 VSK-PTC001 SQK-RBK004 SQK-RPB004 SQK-RBK114-24 SQK-RBK111-24 SQK-RBK114-96 SQK-RBK111-96 SQK-RBK001 SQK-RBK110-96 SQK-RAB201 EXP-PBC001 SQK-MLK114-96-XL SQK-NBD114-96 SQK-NBD111-96 SQK-RLB001 EXP-NBD196 SQK-NBD111-24 EXP-NBD114 SQK-NBD114-24 EXP-NBD104 VSK-VMK001 EXP-NBD103 EXP-PBC096 SQK-PCB114-24 VSK-VMK004 SQK-PCB111-24 SQK-RAB204 SQK-PCB110 SQK-PCB109 SQK-MLK111-96-XL SQK-LWB001 SQK-PBK004 SQK-16S114-24 SQK-16S024. "
  
  The thing is, i do not see SQK-NBD114-96 there; I would like to know if it's still OK to specify this despite not being one of the listed kits?
  
  3. If I did not specify the -emit fastq option, the demux option would have produced a bam output. In fact, dorado seems to tend towards producing unsorted BAM files. I am wondering how this integrates into previous workflows that would involve NanoFilt to set, say a Q20 threshold or higher?
  
  Thank you in advance,

**Comment by dotPiano** [comment]
Regarding point 2, SQK-NBD114-96 is actually in the list, just not in the order you would expect ;)

**Comment by tijyojwad** [comment]
Hi @echovald1 ,

> if it will produce a single demultiplexed fastq output file with the --emit fastq flag

`dorado` will produce a single fastq per barcode + one for unclassified. Basically it will look like the following, except with `fastq` instead of `bam`.
```
$ dorado demux --kit-name SQK-RPB004 --output-dir /tmp/demux reads.fastq

$ ls -1 /tmp/demux
SQK-RPB004_barcode01.bam
SQK-RPB004_barcode02.bam
SQK-RPB004_barcode03.bam
...
unclassified.bam
```

>  i do not see SQK-NBD114-96 there

ah sorry about that, as @dotPiano mentioned it's there but the ordering is unexpected. we will fix the ordering so its more logical and easier to find kit names.

> I am wondering how this integrates into previous workflows that would involve NanoFilt to set, say a Q20 threshold or higher

I'm not super familiar with `NanoFlit` pipeline, but in dorado you can basecall + barcode classify together (details [here](https://github.com/nanoporetech/dorado#in-line-with-basecalling) ). with that you can also specify a `--min-qscore` to filter out any reads below a certain threshold. Alternatively, a BAM can be converted to `fastq` using `samtools` as well (http://www.htslib.org/doc/samtools-fasta.html)
