### ISSUE TITLE
Aligner crashing Terminal

### ISSUE THREAD

**Issue by SanityTree** [nanoporetech/dorado#421]
Hello,

I wanted to use some of my old R9.4.1 data to test the new demultiplexing commands. I started with a batch of fast5's which consist of 10 barcoded samples, I used the basecaller including the barcode kit name and barcode both ends option. I followed this using the demux command with no-classify so that it used the classification from the basecaller. 

I then wanted to align the output bam files from the demultiplexing using the following command:

$ dorado aligner ./reference.fasta ./EXP-NBD114_barcode15.bam -t 8

This caused the terminal to start spewing some non-sensical symbols before returning ";c62;c62;c62;c62;etc".

Is there anything I am doing obviously wrong that I am missing? 

To circumvent it I had to convert the .bam output from the demultiplexing to a .fastq file and use minimap2 using the same reference file. After sorting and indexing the resulting .bam file that gave the same result from when I used guppy/minimap2 previously. I also tried to input the .fastq into the aligner with the same issue.

**Comment by tijyojwad** [comment]
Hi @SanityTree - I would expect this to work. I'll repro this locally and get back to you with what I find.

**Comment by tijyojwad** [comment]
Hi @SanityTree - I just ran through the following steps locally and was able to get an aligned BAM output.

Using the test data in our repository under `tests/data/barcode_demux/read_group_test`, I ran

1. `dorado basecaller --kit-name SQK-RBK114-96 dna_r10.4.1_e8.2_400bps_hac\@v4.2.0/ tests/data/barcode_demux/read_group_test | dorado demux --output-dir barcode-output --no-classify`
2. `dorado aligner ~/references/ecoli-index.mmi ./barcode-output/ > test.bam`
3. `samtools view -h test.bam | less`

`dorado aligner` streams a BAM output, and it needs to be piped into a file or `samtools view` cmd. Looking at your cmd again, I'm wondering if you're just seeing the binary data being rendered in your terminal. So can you try write that output to a file and then `samtools view` it?

If that's the case, it does mean that we have a bug... When output to `tty` we should be writing SAM instead of BAM. We will log that as a bug and fix it.

**Comment by SanityTree** [comment]
Hello,

That makes perfect sense, I just altered my code to include "> barcode15.bam" and the aligner ran as expected. I then used samtools view to examine it like you suggested, and looks great. It did not occur to me to test piping the output into a new file. 

Thank you for working on this!
