### ISSUE TITLE
multiplexing workaround?

### ISSUE THREAD

**Issue by derekstein** [nanoporetech/dorado#44]
What the work around for no multiplexing functionality or alignment if your running an M1 Mac ?

**Comment by vellamike** [comment]
Right now this is something we're working on, in the meantime I'm afraid the solution would be to use Linux or Windows.

**Comment by incoherentian** [comment]
> What the work around for no multiplexing functionality or alignment if your running an M1 Mac ?
I think the silly answer is to CPU basecall+demultiplex using guppy and a FAST.cfg. Then you can do GPU-accelerated basecalling on the demultiplexed FAST5 (or POD5) using SUP or HAC in Dorado. Hypothetically -- I've never used a Mac for MinKNOW/guppy/dorado :)

> Right now this is something we're working on, in the meantime I'm afraid the solution would be to use Linux or Windows.
@vellamike Could you possibly give a brief update on dorado demultiplex support progress? 
I want to start work on a new pipeline with our bioinformatician and ONT has made it clear Dorado is the future for LR basecalling. Would be nice to have it in there from the outset rather than have to swap out guppy later, particularly since Dorado doesn't support the easy-to-access P100 nodes I'd run guppy on :(

**Comment by iiSeymour** [comment]
Dorado v0.4.0 has multiplexing classification and demultiplexing support.

See https://github.com/nanoporetech/dorado#barcode-classification
