### ISSUE TITLE
add -b/--batchsize to dorado_basecall_server

### ISSUE THREAD

**Issue by lpryszcz** [nanoporetech/dorado#456]
Hi, could you please add `-b/--batchsize` to `dorado_basecall_server`? It runs out of vRAM for us.

**Comment by MarkBicknellONT** [comment]
Hi @lpryszcz , it certainly would be possible to add the ability to set the batchsize of the caller in the dorado_basecall_server, but we have an automated system that tries to set a suitable batch size based on the available VRAM in the cuda device you are running with.  Can you let us know a little bit about what model you are running and what hardware you are trying to run it on?
Thanks!

**Comment by lpryszcz** [comment]
thank you!

**Comment by lpryszcz** [comment]
hi, I can see `--batch_size_scale_factor` was added in v7.2.13. thanks!

**Comment by frumencelab** [comment]
Hello, 
could you please provide a bit more description on the use of --batch_size_scale_factor? Could this option also be used on MinKNOW by modifying the app_conf in order to optimize basecalling and VRAM usage for small GPUs? Thank you in advance for your help.

**Comment by MarkBicknellONT** [comment]
Hi @frumencelab ,
Sure, the `--batch_size_scale_factor` argument is used to scale the maximum memory fraction of the _available_ GPU memory that the CUDA caller will use.  If something external is already running using 3GB on an 11GB card, there will be 8GB actually available for use. A `--batch_size_scale_factor 0.25` will tell dorado that it can use up to ~2GB of that memory for a CUDA caller.  There are some other allocations (e.g. model weights themselves), so it won't be exact, but it allows you to exercise some control over how much memory the basecaller will use.
Yes, you can use the argument in the app_conf file or in the doradod daemon on Linux MinKNOW installs in order to change how the memory is used.
