### ISSUE TITLE
Guppy like output format

### ISSUE THREAD

**Issue by christopher-vollmers** [nanoporetech/dorado#472]
Hi,

We are moving our workflows over from guppy to dorado atm and are running into the issue that dorado formats its output differently from guppy. Our downstream C3POa analysis  took advantage of guppy creating a fastq for each pod5 file it basecalled. We wouldn't need that file-to-file match but the batched output was super useful for doing live processing which can save a lot of time. Any chance you could add that feature especially when using --emit-fastq?

Best,
Chris

**Comment by Xuanpei-Zhai** [comment]
Hi,

I've also encountered this issue. I have written an additional script to split the fastq files generated by dorado. Although this step isn't particularly challenging, I believe it's an area that could be improved. Handling a large fastq file can be inconvenient.

Best regard

**Comment by tijyojwad** [comment]
Hi - 

We currently don't have plans to output batched files from dorado, but there a few things that can be done to get the output you want - 

1. the input to dorado itself could be batched - i.e. run dorado on a subset of pod5s at a time. then dorado could be looped over multiple such subsets to generate several smaller fastq or BAM files.
2. the output of a dorado run could be piped into a tool that can batch records into smaller files. this may be better since you can even control how you want to balance the file sizes , e.g. instead of just number of reads you can also partition based on number of bases in the reads to keep file sizes more uniform.
