### ISSUE TITLE
Does 5mCG_5hmCG@v3 have bugs?

### ISSUE THREAD

**Issue by ymcki** [nanoporetech/dorado#488]
I noticed that 0.4.1 supports 5mCG_5hmCG@v3 but 0.4.3 replaces it with 5mCG_5hmCG@v3.1 and v3 is gone.

Does that imply there are bugs in v3, such that it is better to stick with v2 for 0.4.1?

**Comment by tijyojwad** [comment]
Hi @ymcki - yes there was a configuration issue with the v3 model and we released a patch update (0.4.2) to fix that - https://github.com/nanoporetech/dorado/releases/tag/v0.4.2

You should still be able to run the v3.1 model using the 0.4.1 dorado build - you'll just need to pass the model path directly since the internal model list isn't aware of the newer version.

**Comment by tijyojwad** [comment]
yes correct that should work

**Comment by ymcki** [comment]
Thanks for your reply. Will this new model also works with 0.3.x and 0.2.x?

**Comment by tijyojwad** [comment]
It may, but I would strongly suggest using newer versions since many bug fixes and stability improvements have gone in since then.
