### ISSUE TITLE
Option for output

### ISSUE THREAD

**Issue by mbhall88** [nanoporetech/dorado#499]
It would be nice to have an `--output` option to specify a path for the output from basecalling. I know you get the output on stdout, but sometimes having an option is more convenient.

**Comment by vellamike** [comment]
Hi @mbhall88 , this isn't something we are currently intending to add support for. What is the situation whereby piping stdout to a file is inconvenient?

**Comment by mbhall88** [comment]
In certain scripting contexts this can inconvenient, such as passing a dorado command to a subshell. `--output` is also IMO just cleaner and provides more clarity - nearly all popular/common bioinformatics tools provide this option. It also gives you more control over handling errors relating to output.

**Comment by HalfPhoton** [comment]
Closing this issue as this is not something that we intend to support in the near future

**Comment by mbhall88** [comment]
I don't really see why/how this would be such a difficult option to add?

**Comment by vellamike** [comment]
Hi @mbhall88, the design of Dorado in this regard follows the Unix philosophy. By not hardcoding file output functionality, Unix tools are more flexible. Users can decide how they want to handle the output, whether it be displaying it on the screen, redirecting it to a file, or piping it to another command for further processing. This is usually done with the `>` operator for redirecting output to a file, or the `|` operator for piping the output to another command. This design encourages the composition of small utilities to achieve complex tasks.

I do understand that this can be a controversial design decision, not just for Dorado but for many other tools. If there are any situations where you encounter a specific challenge because of this we would be glad to help.

**Comment by mbhall88** [comment]
I am very aware of Unix philosophy, but I don't see how adding an `-o` option wouldn't really impact this? Tools such as samtools are very "Unix-y" but they still provide an `-o` option. I can still achieve very complex tasks with samtools - the `-o` option does not impede this.

I don't really see this as a controversial design choice either; keeping stdout as the default output would definitely make sense. So you would only be adding an alternate option that a user has to go out of their way to select.

At the end of the day, all I can do is request a feature, and if ONT doesn't want to implement it then so be it. Others seem to agree it would also be useful given the reactions to the first comment though.

**Comment by hiruna72** [comment]
Hello, 

There's no easy way to redirect the `stdout/stderr` to a file when you run a program through `CLion` IDE. 

When I was integrating slow5 support for dorado it would have been easier if only `stderr` was printed to the terminal.
![image](https://github.com/nanoporetech/dorado/assets/23216727/37f2f303-4c65-4db5-83b6-c4687949d144)


Hence, I find having `-o` option very useful for many debugging purposes.

**Comment by Psy-Fer** [comment]
I also second having an optional -o.

I also wouldn't call dorado a "small utility" tool. It is way too complex for that. Like including alignment, demuxing, adapter trimming, etc, departs from piping tools together, and presents dorado as a singular pipeline for preparing data for analysis tools after the alignment step.
