### ISSUE TITLE
Dorado standalone  vs Dorado server

### ISSUE THREAD

**Issue by hasindu2008** [nanoporetech/dorado#569]
How do we know the corresponding Dorado standalone version that corresponds to a particular Dorado server version? For instance, when Dorado server v7.2.13, how do we deduce the Dorado standalone version that gives identical results?

**Comment by hasindu2008** [comment]
That would be very helpful to include such an archive or some version mapping information somewhere, otherwise, it will become a nightmare to map these different versions once there are dozens of versions from each software in future.

Also, I have another question. In Guppy versions, the models were available in the archive itself. However, in Dorado server, it seems that they are downloaded on demand. I having an error while downloading on our supercomputing nodes, because the GPU nodes there do not have direct Internet access. Only, certain nodes in the data movement queue have such internet access. Is there a command or something that I can provide to download all the models in dorado-server? I know this is possible in dorado standalone, couldn't find how to do it in dorado-server.

**Comment by MarkBicknellONT** [comment]
Hi @hasindu2008 ,

There's not a command in the dorado_basecall_server to download the full set of models, but you do have two options here.  
- Use the `dorado download` command from the latest standalone dorado to download all the models to a folder, then package up that folder for use on your cluster.
- Extract the models from a MinKNOW installation, as they are all packaged into MinKNOW for every release (in order to avoid exactly the issue you are seeing for offline nodes).
Once you have a copy of the models, you can tell the dorado_basecall_server to use the pre-downloaded models by using the `--dorado_model_path` argument to point it at the folder containing all the models.

In future we can look at simply packaging the models into the dorado_basecall_server package so you don't need to do this extra step, I think that would make life easier.

Kind regards,
Mark
