### ISSUE TITLE
struggling with dorado

### ISSUE THREAD

**Issue by mocherry** [nanoporetech/dorado#641]
Dear Community,

I am struggling with Dorado.
The task: call m6A modification from a sequencing run producing fast5 files. Unfortunately, the epi2me program does not run on Windows but produces unresolvable errors (as of now).
So we tried Dorado, but encountered also errors
this is the input on the command line:
dorado basecaller rna004_130bps_sup@v3.0.1_m6A_DRACH@v1, C:\dorado\eab --modified-bases m6A_DRACH > 20files.bam

the fast5-files are in: C:\dorado\eab

this is the error message:
[2024-02-20 19:03:20.965] [error] Unknown modification variant: '' - Choices: m6A_DRACH, 5mCG_5hmCG, 5mC_5hmC, 5mCG, 5mC, 6mA
[2024-02-20 19:03:20.966] [error] Failed to parse model argument. Failed to parse modified model arguments

Help would be appreciated. Thanks and best,
Matthias

**Comment by HalfPhoton** [comment]
Hi @mocherry, 

I believe there are a couple of issues with your command here.

Firstly, the first positional argument should be the simplex model [complex](https://github.com/nanoporetech/dorado?tab=readme-ov-file#automatic-model-selection-complex) _or_ path, because you're using fast5s you must use a model path.  It looks like you're passing in a mods model here and you have a trailing comma.

We also need to download the simplex model first as only the model complex automatically downloads simplex models. The model that it looks like you want to use is `rna004_130bps_sup@v3.0.1` with the `m6A_DRACH` mods.

Can you try the following please:
```
dorado download --model rna004_130bps_sup@v3.0.1
dorado download --model rna004_130bps_sup@v3.0.1_m6A_DRACH@v1
dorado basecaller rna004_130bps_sup@v3.0.1 --modified-bases m6A_DRACH C:\dorado\eab  > 20files.bam
```

Kind regards,
Rich

**Comment by mocherry** [comment]
Hi Rich,

thank you so much.

Best,
Matthias
