### ISSUE TITLE
Feature request: output sorted bam

### ISSUE THREAD

**Issue by billytcl** [nanoporetech/dorado#642]
I'm not sure if I'm doing something wrong, but I am using dorado to basecall/align/demux, and it doesn't seem to output sorted bam files. MinKNOW and ont-dorado-server and guppy do this automatically when aligning. 

It's not a big deal (as we can add it to our pipeline), but it is creating an extra file and breaks expectations based on what previous ONT basecalling software was doing before!

**Comment by ethan-mcq** [comment]
Here you go: 
```
dorado basecaller hac pod5s/ --reference ref.fa | samtools sort - > output.bam
```

**Comment by billytcl** [comment]
I'm not exactly certain on how piping and its buffers work, but if sorting is much slower than the basecaller wouldn't it make the whole process really slow?

**Comment by ethan-mcq** [comment]
Yes, it will hurt processing speeds, but the alternative is using a tmp file that you delete in your scripts.

**Comment by HalfPhoton** [comment]
Hi @billytcl,
Just a quick update that this feature has been added and will be available in the next release of Dorado.

**Comment by tijyojwad** [comment]
@billytcl The output of dorado aligner will not be sorted and indexed bam files if the output is written to a file (using the new `-o` option). Demux now has a `--sort-bam` option to output sorted bams too, but this only works if trimming is disabled (since trimming affects the reads themselves and invalidates the alignment). If you want to trim, I would suggest running demux before alignment.
