### ISSUE TITLE
No duplex pairs file provided, pairing will be performed automatically

### ISSUE THREAD

**Issue by sidi-yang** [nanoporetech/dorado#655]
Hi, 

I'm doing the duplex base calling using dorado.

And I got output of the first line:

`
[2024-02-28 11:30:42.239] [info] > No duplex pairs file provided, pairing will be performed automatically`

Just wondering what's this "pairs file"? Do I have to provide such file when running dorado?

**Comment by malton-ont** [comment]
Hi @sidi-yang,

Dorado has two methods for determining pairs of reads to combine in duplex mode. The first is "automatic", and uses various heuristics to attempt to assign template and complements reads. This is the appropriate mode in the majority of cases.

The other method is to explicitly provide a file which lists pairs of template/complement read-ids - this is useful if you have performed some upstream analysis in determining pairing yourself (such as when using [duplex-tools](https://github.com/nanoporetech/duplex-tools)) but otherwise is not necessary.

**Comment by sidi-yang** [comment]
Thank you very much!
