### ISSUE TITLE
About  model complex  

### ISSUE THREAD

**Issue by Yang990-sys** [nanoporetech/dorado#681]
Hello,

I want to  detect 6mA, 5mC, and 5hmC for R10 DNA with Dorado, so I need to use three models , using the Automatic model selection complex mentioned in the documentation.

However, I found that unlike the basecall of  single model that can specify a model directory, this method requires three models in the current directory, otherwise it will be redownloaded . Is there a method to specify directories for multiple models ? It is indeed possible to temporarily resolve the issue through soft links, but I would still like to inquire if there is a better way to handle it.

**Comment by HalfPhoton** [comment]
We've decided to add this as a feature.

**Comment by malton-ont** [comment]
@Yang990-sys,

If you'd prefer use previously downloaded models for modbase calling you can specify `--modified-bases-models <path_to_model_1>,<path_to_model_2>` as well as the full path to the basecalling model (i.e., don't use the automatic model detection).

Note that you actually only want 2 models here rather than 3 - the `5hmC_5mC` detection is a single model, and then you can add in the `6mA` as well.

**Comment by HalfPhoton** [comment]
Hi @Yang990-sys
The `--models-directory`  option has been added to [dorado-0.8.0](https://github.com/nanoporetech/dorado/releases/tag/v0.8.0).

Thanks for the feature request!

Kind regards,
Rich
