### ISSUE TITLE
Windows - Dorado 0.1.1 libwinpthread-1.dll not found System Error

### ISSUE THREAD

**Issue by husamia** [nanoporetech/dorado#70]
I am getting this error message when I run dorado.exe [dorado-0.1.1+eb48766-win64]

![image](https://user-images.githubusercontent.com/13439952/210416478-550bfd46-9cad-4f78-80dd-757b27c4fa6f.png)

**Comment by Delayed-Gitification** [comment]
I am also having this error

**Comment by Delayed-Gitification** [comment]
I fixed it with the following:

If you're missing libwinpthread-1.dll it means you're missing the entire MinGW toolchain and you'll have many more problems with other DLLs. Instead of adding this single DLL, install the entire MinGW toolchain to avoid further issues.

1. Install [MSYS2](https://www.msys2.org/) x64
2. Open MSYS2 MinGW x64 command prompt
3. Run pacman -S base-devel mingw-w64-x86_64-toolchain to install the GCC toolchain (all components)
4. Add c:\msys64\mingw64\bin to the System PATH_


From https://stackoverflow.com/questions/28907304/cc1-exe-system-error-libwinpthread-1-dll-missing-but-it-isnt

**Comment by husamia** [comment]
the previous version either didn't require it or it was included. I wanted to make sure going forward it will continue to work for me

**Comment by Albertcarce1997** [comment]
I had the same issue, however, I was able to solve it by running the dorado.exe using the comand prompt. 

Open the comand prompt and type:  "C:\the\path\to\dorado.exe"

Then you should be able to run it. 

Hope it helps!

**Comment by Delayed-Gitification** [comment]
@Albertcarce1997 I'm glad that worked for you, however it didn't work for me until I installed MSYS2
