### ISSUE TITLE
Clarification on simplex reads which have duplex offsprings (dx:i:-1)

### ISSUE THREAD

**Issue by sadikmz** [nanoporetech/dorado#720]
Hi

Could you please clarify who "simplex reads which have duplex offsprings" are and their utilities? Apology if this has been asked before but cant find a resource that explain about it. 

Looking the nanopore duplex chemistry my understanding is that there are two types of based called reads; 

- those who have been called from one of the strand as they passes through the nanopore - simplex calls
- and those who have been called from both of the strand as they passes one after the other in same nanopore - duplex calls

This leaves me to ask who **simplex reads which have duplex offsprings** are? Are they a copy of either of the simplex calls of the duplex calls (either the first sequenced strand or its complementary)? if that is the case why do we need them? In my end, **simplex reads which have duplex offsprings** contain more of less than q-10 reads that simplex and duplex reads. 

Any clarification much appreciated.

**Comment by vellamike** [comment]
Hi @sadikmz,

Apologies for the delay in replying to this. 

> Are they a copy of either of the simplex calls of the duplex calls (either the first sequenced strand or its complementary)? 

Yes, they are the two simplex calls which combine to form a duplex call.

> if that is the case why do we need them?

There are situations where they can be useful - for example, sometimes the template read is much longer than the duplex read because the complement is truncated. However, if you want to avoid double-counting they should simply be eliminated from your analysis.

**Comment by vellamike** [comment]
Closing this issue as the meaning of `dx:i:-1` has been clarified.
