### ISSUE TITLE
Dorado Demultiplexing

### ISSUE THREAD

**Issue by akholwad** [nanoporetech/dorado#722]
# Issue Report

I am running dorado demultiplexing using custom barcodes, and the majority of my reads end up unclassified. 

My custom TOML file includes the following trailing flank:

mask1_rear = "AGRGTTYGATYMTGGCTCAG"

Are variable nucleotide sites (R, Y, M) supported by the dorado demultiplexing?

**Comment by plypa** [comment]
Hi, we fixed this by using a custom compiled version with 3 lines changed in dorado/demux/BarcodeClassifier.cpp lines: 32-35

   ```
    static const EdlibEqualityPair additionalEqualities[13] = {
            {'N', 'A'}, {'N', 'T'}, {'N', 'C'}, {'N', 'G'}, {'N', 'U'}, {'M', 'A'}, {'M', 'C'}, {'R', 'G'}, {'R', 'A'}, {'Y', 'T'}, {'Y', 'C'}, {'K', 'G'}, {'K', 'T'} };
    placement_config.additionalEqualities = additionalEqualities;
    placement_config.additionalEqualitiesLength = 13;
```

could this be integrated?

**Comment by malton-ont** [comment]
Hi @akholwad,

We don't have any plans to do this at present. Although it's simple to do (as you've demonstrated), we'd need to investigate any potential performance impact before we considered making such a change, especially since opening up to one ambiguous base code would probably mean we'd need to open up all of them.
