### ISSUE TITLE
5hmC modification calling with R10.4.1 models

### ISSUE THREAD

**Issue by assafgrw** [nanoporetech/dorado#79]
Hello and thak you for all the recent developments.
I have a question regarding base calling of 5hmC bases on V14 data which I am not able to do so far:
I have a data set that was running on V14 cells (R10.4.1), post run I was basecalling using Dorado on a command line and was using modbam2bedmethyl to extract 5mC and 5hmC. 
For 5mC I got reasonable results while there were 0 5hmC modifications detected over the whole data even though I Know that there are 5hmC in my sample.
Am I doing something wrong? or does the model is not yet trained well on the V14 chemistry? 
To extract 5hmC modification I was basecalling using Dorado either with:  "dna_r10.4.1_e8.2_400bps_fast@v4.0.0" or  "dna_r10.4.1_e8.2_400bps_hac@v4.0.0" and "--modified-bases 5mCG_5hmCG" tag. Than I converted the resulted sam file to fastq using “samtools fastq –T MM,ML” aligned it to the reference with minimap2 and was calling modifications with modbam2bedmethyl.
Any Ideas?

**Comment by itslittman** [comment]
@assafgrw There’s a DNA model that has the modified bases in the name. I ran it with dorado, mapped the output, and when dragged it into IGV, I can see the 5hmC and 5mCG sites color coded

**Comment by assafgrw** [comment]
> @assafgrw There’s a DNA model that has the modified bases in the name. I ran it with dorado, mapped the output, and when dragged it into IGV, I can see the 5hmC and 5mCG sites color coded

Thanks for your reply, can you please share the command you run? As I did the same but no 5hmC were called

**Comment by itslittman** [comment]
@assafgrw I did

dorado basecaller --modified-bases-models dna_r10.4.1_e8.2_400bps_fast@v4.0.0_5mCG_5hmCG@v2 dna_r10.4.1_e8.2_400bps_fast@v4.0.0 /path/to/pod5 > ~/path/to/unmapped.sam

then I converted SAM to FASTQ with samtools fastq -T MM,ML unmapped.sam > unmapped.fastq

and then after you map, you do "color by -> modified bases" on the right-click menu in IGV if it doesnt automatically show

**Comment by assafgrw** [comment]
I'll try that, thank you.

**Comment by Flower9618** [comment]
Hi, I would like to know, when you aligned fastq file including MM,ML tag into reference genome with minimap2, Is there MM,ML tag information in the alignment result(.bam)?

**Comment by Flower9618** [comment]
Thank you so much. By the way, after getting the mod.Sam, is there any way to extract 5hmC information, like modbam2bed. Because the position in MM tag is based on exactly sequence as sequences , not the aligned reference sequence.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: itslittman ***@***.***>
发送时间: Thursday, March 23, 2023 8:54:18 AM
收件人: nanoporetech/dorado ***@***.***>
抄送: QIAO, Rong ***@***.***>; Mention ***@***.***>
主题: Re: [nanoporetech/dorado] 5hmC modification calling with R10.4.1 models (Issue #79)


@Flower9618<https://github.com/Flower9618> yes it’ll be there; you’ll see the bases and probabilities in IGV.

―

**Comment by Flower9618** [comment]
Do not worry. Thank you so much for your help. I will try some methods.

发件人: itslittman ***@***.***>
答复: nanoporetech/dorado ***@***.***>
日期: 2023年3月23日 星期四 09:48
收件人: nanoporetech/dorado ***@***.***>
抄送: "QIAO, Rong" ***@***.***>, Mention ***@***.***>
主题: Re: [nanoporetech/dorado] 5hmC modification calling with R10.4.1 models (Issue #79)


@Flower9618<https://github.com/Flower9618> I’m confused as to what you mean - I’m not sure honestly. I just started with DNA seq, I’m pretty new to it. Others here probably know better than I.

**Comment by kaanokay** [comment]
Hi @assafgrw ,

Is that possible to have both 5hmC and 5mC tags in one single bam file for one sample through Dorado? After getting output, usage of modbam2bed allows us to call 5hmC and 5mC from the same bam file, right? I want to have both tags in the same bam file, otherwise there will be a lot of data to store on cluster. I need to save some storage space.

Thanks!
