### ISSUE TITLE
Question about "--no-trim" option for basecalling and demux

### ISSUE THREAD

**Issue by lucyintheskyzzz** [nanoporetech/dorado#825]
I am re-reading the dorado Github page and I noticed this:

"If adapter/primer trimming is done in-line with basecalling in combination with demultiplexing, then the software will automatically ensure that the trimming of adapters and primers does not interfere with the demultiplexing process. However, if you intend to do demultiplexing later as a separate step, then it is recommended that you disable adapter/primer trimming when basecalling with the --no-trim option, to ensure that any barcode sequences remain completely intact in the reads."

I am running this on Loni HPC GPU cluser:
8 GPU Compute Nodes, each with:
Two 24-core Intel Cascade Lake (Intel® Xeon® Platinum 8260 Processor) CPUs.
192 GB memory
600 GB HDD
2 NVIDIA Volta V100 GPU's

Here is an example of how I am running my code:

##ONR012021
/work/kvigil/Programs/dorado-0.6.1-linux-x64/bin/dorado basecaller /work/kvigil/Programs/dorado-0.6.1-linux-x64/bin/dna_r9.4.1_e8_hac@v3.3 --recursive /ddnB/work/kvigil/sandiego/ONR012021/ONR012021/pod5   --kit-name SQK-PBK004 > /ddnB/work/kvigil/sandiego/ONR012021/ONR012021/pod5/hac/ONR012021.calls.bam

##demux
/work/kvigil/Programs/dorado-0.6.1-linux-x64/bin/dorado demux --output-dir /ddnB/work/kvigil/sandiego/ONR012021/ONR012021/pod5/hac/barcodes --no-classify /ddnB/work/kvigil/sandiego/ONR012021/ONR012021/pod5/hac/ONR012021.calls.bam

Is this considered "demultiplexing as a separate step"? Do I need to add the "--no-trim" during by basecalling step so dorado will correctly demultiplex my .bam file in the correct barcode files, so I am not stuck with alot of unclassified reads?

Thanks! Katie

**Comment by tijyojwad** [comment]
Hi @lucyintheskyzzz - what you're running is demuxing "in-line" since it's happening as part of the `basecaller` command. the subsequent `demux --no-classify` is simply splitting the BAM into per barcode BAMs.

if you were to run basecalling first, and then run `demux` cmd to _classify_ the reads with `--kit-name` that would be demuxing as a separate step.

**Comment by lucyintheskyzzz** [comment]
Hi @tijyojwad I ended up using —no-trim and it worked for the demux and I had way more reads and less unclassified. Now I am wondering what tool you recommend for post demux processing to chop off the barcodes and adapters and filter out low quality reads? Fastp? Porechop (discontinued since 2018)? Thanks!

**Comment by lucyintheskyzzz** [comment]
@ireneortega I was told that it does automatically chop barcodes and adapters during demux, but I definitely want to double check. I ended up using fastp anyways to get rid of all the adapters and barcodes and qscore <15.

**Comment by Htrivett** [comment]
Hi @katievigil, how much of an improvement did you see in separating the trimming from its command? I currently have a lot of reads labelled as unclassified and wondered if this was still something you see with the newer versions of Dorado.

**Comment by katievigil** [comment]
Hi @Htrivett I just had decrease in unclassified reads when I did this (I am not sure how much, because I did this a while ago).  I also saw my q-score increase from Q7 to Q14 when I re-basecalled using dna_r10.4.1_e8.2_400bps_sup@v4.3.0 on dorado v0.7.0. 

Here are the scripts I used:

Pod5 basecalling script
/work/kvigil/Programs/dorado-0.7.0-linux-x64/bin/dorado basecaller /work/kvigil/Programs/dorado-0.7.0-linux-x64/bin/dna_r10.4.1_e8.2_400bps_sup@v4.3.0 --no-trim --recursive /ddnB/work/kvigil/vibrio_051424/20240514_1438_P2S-01216-B_PAS53473_fe1ca469/pod5  --kit-name SQK-NBD114-24 > /work/kvigil/vibrio/hac/vibrio.calls.bam

Demux script
#!/bin/bash
#SBATCH -A loni_admintest0    ### Allocation name
#SBATCH -p gpu2 ## queue name
#SBATCH -t 0-05:00:00 ## wall time
#SBATCH -N 1 ## number of nodes
#SBATCH -n 1 ## number of tasks
#SBATCH -c 4 ## number of cores per task
#SBATCH -o demux.out ## standard output file
#SBATCH -e demux.err ## standard error file
#SBATCH -J vibrio_demux ## job name

##demux using dorado

/work/kvigil/Programs/dorado-0.7.0-linux-x64/bin/dorado demux --output-dir /ddnB/work/kvigil/vibrio_051424/20240514_1438_P2S-01216-B_PAS53473_fe1ca469/sup/barcodes --no-classify /ddnB/work/kvigil/vibrio_051424/20240514_1438_P2S-01216-B_PAS53473_fe1ca469/sup/vibrio.calls.bam

## Load Conda environment (if not already loaded) this wont work if python is loaded
module unload python
unset conda
module purge
module load conda
#conda init

## Load samtools
#module load samtools/1.18
source activate samtools-env

## Path to directory containing demultiplexed BAM files
bam_dir="/ddnB/work/kvigil/vibrio_051424/20240514_1438_P2S-01216-B_PAS53473_fe1ca469/sup/barcodes"

## Loop through all demultiplexed .bam files
for demuxed_bam in "$bam_dir"/SQK-NBD114-24_barcode*.bam; do
    # Create output file names for FASTQ files
    output_base="${demuxed_bam%.bam}"
    output_fastq="${output_base}.fastq"

    ## Convert demultiplexed BAM to FASTQ using samtools
    samtools fastq "$demuxed_bam" > "$output_fastq"
done

**Comment by Htrivett** [comment]
Thanks Katie!

So, from this, I'm assuming you left trimming to be done via demux automatically to remove barcodes and adapters? I have rebasecalled with --no-trim to see if I get similar decreases in unclassified. I am using some older data, which was on an R9 flow cell, so I won't be able to update the sup model.

**Comment by katievigil** [comment]
Yes I left trimming to be done via demux automatically to remove barcodes and adapters.
