### ISSUE TITLE
Trimming barcodes behaviour with demux --no-trim

### ISSUE THREAD

**Issue by francesco227** [nanoporetech/dorado#835]
# Issue Report
No trim behaviour using Dorado Demux

## Please describe the issue:
Hi! I'm using dorado demux to demultiplexing my reads after using the kit SQK-NBD114-24 and after using dorado basecalling. 
When I use the option --no-trim (both in combination with --no-classify or with the name of the kit) I would expect to still have the barcodes in the reads. 
After demultiplexing, I obtain a .bam file and using the command samtools fastq I convert the .bam to a fastq. 
The problem is that the reads are exactly the same, and I never find the barcode, either I use the --no-trim option or I don't. 

Thanks a lot!!!! :-)
Francesco

## Run environment:
- Dorado version: 0.6.0+7a6ab9a
- Dorado command:
command without trimming:
dorado demux calls_hac_single_end.bam --kit-name SQK-NBD114-24 --output-dir classified_demux_single_bc_trimmed
command trimming:
dorado demux calls_hac_single_end.bam --kit-name SQK-NBD114-24 --output-dir classified_demux_single_bc **--no-trim**
- Operating system: Ubuntu 22.04.4 LTS
- Source data type (e.g., pod5 or fast5 - please note we always recommend converting to pod5 for optimal basecalling performance): pod5 
- Details about data (flow cell, kit, read lengths, number of reads, total dataset size in MB/GB/TB): kit SQK-NBD114-24

**Comment by tijyojwad** [comment]
Hi, can you share your basecalling command?

**Comment by francesco227** [comment]
~/miniconda3/bin/dorado-0.5.3-linux-x64/bin/dorado basecaller hac Yeast-ITR_3-pod5/ --kit-name SQK-NBD114-24 --barcode-both-ends > calls_hac.bam

(the basecalling and the demultiplexing were done on different computers.)
in this case dorado version is: 0.5.3 and ubuntu version: 20.04 

thanks!!! maybe there is something im missing :-)

**Comment by tijyojwad** [comment]
Hi @francesco227 - since you've specified barcoding during basecalling, the barcodes will be trimmed by default (as mentioned [here](https://github.com/nanoporetech/dorado?tab=readme-ov-file#in-line-with-basecalling-1)). However each read should already be classified.

You can run `dorado demux --no-classify calls_hac_single_end.bam --output-dir classified_demux_single_bc` split the basecalled BAM into per barcode BAMs.

If you want to do barcode classification after basecalling, you can remove the `--kit-name` option from the `dorado basecaller` command.
