### ISSUE TITLE
Dorado Conda install

### ISSUE THREAD

**Issue by AzlanNI** [nanoporetech/dorado#852]
Hello everyone! 

I am currently writing a pipeline with Snakemake. And i wanted to include dorado into it. So know i looked up if dorado has any conda installs but i did not find any that are working for me. I tried the following: 
conda install hcc::dorado 
conda install hcc::dorado-gpu

The gpu Version did not work at all to install. And the other version does end with a successful install but i can not call dorado basecall as command it just allows me to call dorado_basecall_server . So know my question would be is there any way to install dorado as dependency with conda. Or if this is not possible and i have to put dorado outside of the Pipeline.  If it is not able to install dorado as dependency with conda would there be any other ONT basecaller which use pod5s of bacterial Data to analysze 5mC and 6mA modifications. 

I would be very grateful for any advice! 
kind regards,
Azlan

**Comment by tijyojwad** [comment]
Hi @AzlanNI - `hcc` is not maintained by us. The official `dorado` builds are only available for download from our GitHub repo - https://github.com/nanoporetech/dorado?tab=readme-ov-file#installation .

> would there be any other ONT basecaller which use pod5s of bacterial Data to analysze 5mC and 6mA modifications

not that I'm aware of. and we strongly recommend using `dorado` for calling any ONT data so that you get the best and most updated support for your experiments.
