### ISSUE TITLE
read filtering issue during basecalling

### ISSUE THREAD

**Issue by luigilamparelli** [nanoporetech/dorado#937]
# Issue Report

Hello,

I was trying to get statistics of the % of pass and fail reads in a flow cell after parallelized basecalling by single pod5 on an HPC. I've seen that the number of reads marked as pass in the dorado basecaller log is not equal to the number of reads in the resulting bam file and, consequently, in the dorado summary report. I will put here as example a single pod5 (but I have many others with the same problem) with relative numbers.

1. From the dorado basecaller log (with the `--min-qscore` parameter set to 10), I'm using the `Simplex reads basecalled:` and `Simplex reads filtered:` strings to extract the number of reads, obtaining respectively 680 and 3320 reads (for a sum of 4000 that is expected since is an old run with 4000 reads per pod5)
2. The resulting bam have 681 reads, 1 more respect to the declared number in the log file
4. The dorado summary on the bam have 681 rows, one per read as expected from the number of reads of the bam file
5. Of 681 rows, 30 have the column `mean_qscore_template` which is < 10 (the threshhold I've used for filtering with dorado basecaller)
6. Of these 30 reads, I've taken the one with the lowest qscore on the summary which is 8.82051
7. The qscore flag in the bam is `qs:f:8.82051`, consistent to what is reported on the summary
8. I've tried to manually compute the mean qscore by myself using the py script attached and I got a result of 21.21323529411765 which is very confusing.

This is what I've seen and tried, but I'm not sure if all my assumptions are correct. At this point, I'm not sure if:

1. The way the `qs:f:` bam flag is computed is the same as I computed the mean qscore
2. The `--min-qscore` parameter of dorado basecaller is acting on the flag or some other computations
3. The column `mean_qscore_template` in the summary is the same qscore as the dorado basecaller parameter

Despite these assumptions, the fact that the log says there are 680 reads while in the bam there are 681 reads is for sure some kind of bug. You will find attached a sam with the read, the complete pod5 dorado summary, the dorado basecalling log and the py script I've used to compute the mean qscore of that specific read.
[compute_mean_qscore.py.txt](https://github.com/user-attachments/files/16174569/compute_mean_qscore.py.txt)
[dorado.log](https://github.com/user-attachments/files/16174571/dorado.log)
[sequencing_summary.tsv.txt](https://github.com/user-attachments/files/16174572/sequencing_summary.tsv.txt)
[test.sam.txt](https://github.com/user-attachments/files/16174573/test.sam.txt)

A nice addition to all this topic: it would be great to have some basecalling stats in a tabular file rather than extracting these infos from the log file.

Thank you for your help!

## Steps to reproduce the issue:

1. pod5 convert fast5 --threads ${cpus} --output ${pod5} ${fast5}
2. dorado basecaller --min-qscore 10 ${sup_config} ${pod5} --modified-bases 5mCG_5hmCG > ${bam} 2> dorado.log
3. dorado summary ${bam} > sequencing_summary.tsv

## Run environment:
- Dorado version: 0.7.2

**Comment by malton-ont** [comment]
Hi @luigilamparelli,

I think you have three questions here, so let me take them in order.

### Why do I have 681 records when dorado reports 680 reads basecalled?
The 680 reads is the number of reads _basecalled_. Due to read splitting (and also alignment, though you're not doing that), a single basecalled read may generate multiple records. You can check for this by looking for reads with a `pi` tag in the output BAM file:
```
samtools view ${bam} --expr '[pi] && [dx]!=1' | wc -l
```
This outputs the count of reads that have a `parent_read_id` set and are not duplex reads (just for completeness - none of your reads will be duplex reads, as you're not running duplex...). I would expect this to give a value of 2 for your data - one read was split into 2 records.

### Why do I have reads with a qscore below my filter level?
Dorado performs filtering quite early in the pipeline in order to reduce the amount of work that is required by the downstream nodes. This means the qscore filter is applied before adapter/primer trimming (which is on by default) and barcode trimming (which you're not doing). If the adapter sequence qscore tended to be higher than average for the read, this could mean that the qscore of the trimmed read that is output to file drops below that threshold. You can verify this by adding the `--no-trim` flag to your basecall command - you should see that those reads that were below threshold are now above it.

### Why does my script calculate a different qscore?
Your script does not calculate the mean qscore in the same way as dorado. Dorado calculates the mean _error_ and converts that to a qscore. It also discards values from the first 60 bases for reads longer than 60 bases. The method used by dorado looks like this:
```
import math

# Quality string
quality_string = ";;;;;?<<<?GJI>>>>>>=<=<<=>>A@A??@==<8889?>=<<<;<<;;?==<;::;;<99:::7666444<2+')933;<<=???CA?>=>=>>??51)))+&&(('&&&&''))&%&%%&&'()))))&%%$"

# Truncate string
quality_string = quality_string[60:] if len(quality_string) > 60 else quality_string
# Convert ASCII to Phred quality scores, then to estimated error
errors = [10**(-(ord(char) - 33)/10) for char in quality_string]
# Calculate mean error
mean_error = sum(errors) / len(errors)
# Convert back to qscore
mean_qscore = -10 * math.log10(mean_error)

print(mean_qscore)
```
This gives `8.820508383440712`, which matches the result from dorado.

**Comment by malton-ont** [comment]
@luigilamparelli,

Minknow pass/fail filtering is based on qscore, yes. The default cut-offs vary based on the model type - in current versions this is 8/9/10 for fast/hac/sup. I believe there are also read length filters available. Further Minknow questions might be better asked on the community though.

**Comment by luigilamparelli** [comment]
Dear @malton-ont,

thank you for your answers, now everything is clear. I might say though that, from the current documentation about the summary or the dorado param is not clear (if all these infos are written somewhere I was not able to find them) and the info or the name of the parameter may be a bit misleading.

Anyway, thanks again for the clarification, everything is clear now!
