### ISSUE TITLE
RNA004 polyA question

### ISSUE THREAD

**Issue by Yang990-sys** [nanoporetech/dorado#947]
Hello, 
    We  created a nucleic acid molecule structure like "3' ---- ADAPTER ----DNAadapter---- poly(A) ---- RNA ---- 5' "，and we need to accurately estimate the length of polyA.  What changes does Dorado need to make ? Can you give me some guidance on changing ？

Thank you.

**Comment by malton-ont** [comment]
Hi @Yang990-sys,

There are currently no options to customize dorado for RNA polytail detection, but I think this might just work.

For RNA models, dorado determines the approximate position where the DNA adapter ends by looking at the median signal value over a sliding window on the raw signal. Assuming your additional `DNAadapter` looks similar in the median signal to the `ADAPTER` then dorado should detect that transition instead.

Have you tried running dorado with the `--estimate-poly-a` flag? Are the results sensible?

**Comment by Yang990-sys** [comment]
Yes, I tried on a small dataset and the result was that most polyA was detected, while a small portion was not detected, and the accuracy is unknown.
Dorado result summary :
        PolyA tails called 130757, not called 2616, avg tail length 75
Most of the undetected parts can also see polyA tails from fastq：
![image](https://github.com/user-attachments/assets/878996b7-3b3c-4e77-b527-a6d672ff34f4)

So I have two questions here: 
         1. Does this mean that the detected part is correct? 
         2. If the starting point of the adapter is determined based on the median signal, does it mean that the same sequence will have similar median signals? After exporting the MV information, calculate the median signal of DNAadapters in all reads, and then replace the values in polyA identification. Will this make the results more accurate?

**Comment by malton-ont** [comment]
@Yang990-sys,

1. Those called/uncalled values look reasonable. You would know better than I what length tail you are expecting.
2. Dorado is looking for the change in the median value due to the transition from DNA to RNA. It is possible that the thresholds we use are not universally applicable, especially if you have introduced a new adapter. As I said, there is currently no way to customise this value, short of editing the source code and recompiling dorado yourself.
