### ISSUE TITLE
Different number of basecalled reads between V100 and A100.

### ISSUE THREAD

**Issue by vadanamu** [nanoporetech/dorado#960]
# Issue Report

## Please describe the issue:

I ran Dorado basecaller with exactly the same options & datasets on V100 and A100, and the numbers of basecalled reads were slightly different.
The basecaller model was rna004_130bps_sup@v5.0.0.

Running on V100:
 * Simplex reads basecalled: 4,403,154
 * Simplex reads filtered: 114,277

Running on A100:
 * Simplex reads basecalled: 4,403,248
 * Simplex reads filtered: 114,025

## Steps to reproduce the issue:
Run Dorado basecaller rna004_130bps_sup@v5.0.0 model on A100 and V100.

The discrepancy did not occur when basecalling a single or a few POD5 files. 
It only occured when basecalling the whole sequencing run (~1100 POD5 files).

I don't know if the error is specific to the options I used (--emit-moves --no-trim) or specific to the data.
The data is RNA004 PromethION 2 Solo run, and the sample is in-vitro transcribed human RNA.

## Run environment:
- Dorado version: 0.7.2
- Dorado command: dorado basecaller --reference {_REF_FASTA_PATH_} --chunksize 12000 -x cuda:all --emit-moves --no-trim {_MODEL_PATH_}/rna004_130bps_sup\@v5.0.0 {_INPUT_POD5_PATH_} > {_OUTPUT_BAM_PATH_} (The paths have been redacted.)
- Operating system: CentOS 7
- Hardware: (1) V100-SXM2-32G x4 ; Intel Xeon Gold 5118 x2 (24 phys. cores) ; 0.5 TB memory
- Hardware: (2) A100-SXM4-80G x4 ; AMD EPYC 7543 x2 (64 phys. cores) ; 2 TB memory
- CUDA Driver version: 510.47.03
- CUDA Version: 11.6   
- Source data type : POD5
- Source data location : NFS
- Details about data : RNA004, PromethION 2 Solo,  Estimated N50 = 1.03 kb, Reads Generated = 4.4 M, Estimated bases = 4.24 Gb, Total data produced = 144.14 GB (According to MinKNOW report) 

## Logs

I have attached the traces of the two basecalling runs below. 
They are not the full traces, but only the first 10,000 lines. Also, the paths have been redacted.
Please let me know in case the full traces are needed.
[trace_A100.txt](https://github.com/user-attachments/files/16355727/trace_A100.txt)
[trace_v100.txt](https://github.com/user-attachments/files/16355728/trace_v100.txt)

**Comment by susie-ont** [comment]
Hi @vadanamu - thanks for raising this. Our basecalling models use deep learning algorithms that run slightly differently on different hardware, which can lead to discrepancies in areas with low certainty (low Q-scores) but should not affect high confidence basecalls and reads. This is because of small differences in the arithmetic used by different hardware. The difference in number of basecalled reads is likely due to slight changes in the Q-scores and read lengths that cause borderline reads to pass or fail. 

For the best reproducibility we recommend you use the same hardware to basecall. The GPU used to basecall is also output as a tag in the BAM file if you want to keep track of this.
